Title: Gideon Oluwafemi Adewusi
logo: headshot.jpg
description: A data analysis with 4 years experience using excel for report automation, sql for data manipulation and interrogation and power bi for business intelligence reporting.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
